<?php
/**
 * @file
 * dfc_bean.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function dfc_bean_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['bean-clubhouse-boat-tour'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'clubhouse-boat-tour',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-clubhouse-book'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'clubhouse-book',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-clubhouse-feature'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'clubhouse-feature',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-clubhouse-features-and-highlight'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'clubhouse-features-and-highlight',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-clubhouse-intro-text'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'clubhouse-intro-text',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-clubhouse-location'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'clubhouse-location',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-clubhouse-slideshow'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'clubhouse-slideshow',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-fab-52-intro'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'fab-52-intro',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-fab-52-resorts-top-block'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'fab-52-resorts-top-block',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-footer-copyright'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'footer-copyright',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-header-info'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'header-info',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-home---cta'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'home---cta',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-home---how-it-works'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'home---how-it-works',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-membership-header'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'membership-header',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-title-my-profile'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'title-my-profile',
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'dfc' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc',
        'weight' => 0,
      ),
      'dfc_admin' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dfc_admin',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
