<?php
/**
 * Implements hook_block_info().
 */
function dfc_flop_menu_block_info() {
  $blocks = array();
  $blocks['userflop'] = array(
    'info' => t('User Flop Menu'),
  );
  $blocks['userfloplink'] = array(
    'info' => t('User Flop Link'),
  );
  
  return $blocks;
}

function dfc_flop_menu_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'userflop':
      $block['content'] = array(
        '#markup' =>  dfc_flop_menu_block_flop_view()
      );
      break;
    case 'userfloplink':
      $block['content'] = array(
        '#markup' =>  dfc_flop_menu_block_flop_link()
      );
      break;
  }

  return $block;
}
function dfc_flop_menu_block_flop_link(){
  global $user;
  $user = user_load($user->uid);

  if($user->uid == 0) {
    $link_markup = l('Member Login', 'javascript:void(0)', array('attributes' => array('id' => 'member_info_link'), 'external' => TRUE)); 
  }else{
    $lifetime_points = userpoints_get_current_points($user->uid, 0);
    if(!empty($user->picture)){
      $filepath = $user->picture->uri;
    }else{
      $filepath = variable_get('user_picture_default', '');
    }
    $link_markup = dfc_flop_menu_markup_wrapper(dfc_flop_menu_markup_wrapper($lifetime_points, array('class' => 'flop-link-points-wrapper')).'<a href="javascript:void(0);" id="member_info_link">'.theme('image', array('path' => $filepath, 'attributes' => array())).'</a>', array('id' => 'dfc-user-flop-link'));
  }
  return $link_markup;
}
/*
 * Provides content for the detailed user block, for flop out,
 * displaying larger user image thumbnail + points total
 * + more
 */
function dfc_flop_menu_block_flop_view() {
  global $user;
  $user = user_load($user->uid);

  if($user->uid == 0) {
    $markup = drupal_render(drupal_get_form('user_login_block'));
  }else{
    $uname = '';
    if (!empty($user->field_first_name)) {
      $uname .= $user->field_first_name[LANGUAGE_NONE][0]['value'];
    }
    $uname .= ' ';
    if (!empty($user->field_last_name)) {
      $uname .= $user->field_last_name[LANGUAGE_NONE][0]['value'];
    }
    $uname_markup = dfc_flop_menu_markup_wrapper( check_plain( $uname ), array('class' => 'user-name' ) );

    $ulocation_markup = dfc_flop_menu_markup_wrapper( check_plain( $user->field_city_state[LANGUAGE_NONE][0]['value'] ), array('class' => 'user-city-state' ) );

    $picture_markup = theme('user_picture', array('account' =>$user));
    
    $menu = menu_navigation_links('menu-flop-menu');
    $menu_markup = theme('links__menu-flop-menu', array('links' => $menu));

    $lifetime_points = userpoints_get_current_points($user->uid, 0);
    $monthly_points = userpoints_get_current_points($user->uid, 1);
    $points = dfc_flop_menu_markup_wrapper('DFC Points', array('class' => 'points-title-wrapper'));
    $monthly_points_markup = dfc_flop_menu_markup_wrapper(date('F'), array('class' => 'monthly-title-wrapper'));
    $monthly_points_markup .= dfc_flop_menu_markup_wrapper($monthly_points, array('class' => 'monthly-points-wrapper'));
    $monthly_points_markup .= dfc_flop_menu_markup_wrapper(l('Redeem', '#').' | '.l('Donate', '#'), array('class' => 'monthly_points_links'));
    $lifetime_points_markup = dfc_flop_menu_markup_wrapper('Lifetime', array('class' => 'lifetime-title-wrapper'));
    $lifetime_points_markup .= dfc_flop_menu_markup_wrapper($lifetime_points, array('class' => 'lifetime-points-wrapper'));
    $lifetime_points_markup .= dfc_flop_menu_markup_wrapper(l('Redeem', '#').' | '.l('Donate', '#'), array('class' => 'lifetime_points_links'));
    $points_markup = dfc_flop_menu_markup_wrapper($points . dfc_flop_menu_markup_wrapper($monthly_points_markup, array('class' => 'monthly_points_markup')) . dfc_flop_menu_markup_wrapper($lifetime_points_markup, array('class' => 'lifetime_points_markup')), array('class' => 'flop-points-wrapper'));

    // put it all together
    $markup = $picture_markup . $uname_markup . $ulocation_markup . $menu_markup . $points_markup;
  }
  return dfc_flop_menu_markup_wrapper($markup, array('id' => 'dfc-user-flop'));
}
function dfc_flop_menu_markup_wrapper($markup, $attributes = NULL, $tag = 'div') {
  if ( $tag == 'usermenu' ) {
    $output = '<span class="icon"></span><span class="title">'. $markup .'</span>';
    if (isset($attributes) && is_array($attributes)) {
      if ( isset( $attributes['count'] ) ) {
        $output .= '<span class="count">'. $attributes['count'] .'</span>';
      }
    }
  } else {
    $attrs = '';
    if (isset($attributes) && is_array($attributes)) {
      foreach($attributes as $k => $v) {
        $attrs .= " $k='$v'";
      }
    }
    $output = "<$tag$attrs>$markup</$tag>";
  }
  return $output;
}

function dfc_flop_menu_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_login_block') {
    // replace default list from user.module ~ line 1355 to remove Create..
    $items = array();
    $items[] = l(t('Request new password'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'))));
    $form['links'] = array('#markup' => theme('item_list', array('items' => $items)));
  }
}