<?php
/**
 * Implements hook_block_info().
 */
function dfc_user_blocks_block_info() {
  $blocks = array();
  $blocks['your_membership'] = array(
    'info' => t('Your Membership'),
  );
  $blocks['membership_benefits'] = array(
    'info' => t('Membership Benefits'),
  );
  return $blocks;
}

function dfc_user_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'your_membership':
      $block['content'] = array(
        '#markup' =>  dfc_user_blocks_your_membership_view()
      );
      break;
    case 'membership_benefits':
      $block['content'] = array(
        '#markup' =>  dfc_user_blocks_membership_benefits_view()
      );
      break;
  }

  return $block;
}
function dfc_user_blocks_your_membership_view(){
  global $user;
  $user = user_load($user->uid);
  foreach($user->roles as $role){
    if(in_array($role, array('Silver', 'Gold', 'Platinum', 'Diamond'))){
      break;
    }
  }
  $current_markup = dfc_user_blocks_markup_wrapper('Current Membership Level', array('class' => 'current-membership-title'));
  $current_markup .= dfc_user_blocks_markup_wrapper($role, array('class' => 'current-role'));
  //$current_markup .= dfc_user_blocks_markup_wrapper('Your annual membership is scheduled to auto-renew on ', array('class' => 'auto-renew'));
  $markup = dfc_user_blocks_markup_wrapper($current_markup, array('class' => 'current-membership-wrapper'));
  if($role <> 'Diamond'){
    $upgrade_markup = dfc_user_blocks_markup_wrapper('Want to upgrade?', array('class' => 'upgrade-membership-title'));
    $upgrade_markup .= l('Membership Levels', '/membership');
    $markup .= dfc_user_blocks_markup_wrapper($upgrade_markup, array('class' => 'upgrade-membership-wrapper'));
  }
  return $markup;
}
function dfc_user_blocks_membership_benefits_view(){
  global $user;
  $user = user_load($user->uid);
  foreach($user->roles as $role){
    if(in_array($role, array('Silver', 'Gold', 'Platinum', 'Diamond'))){
      break;
    }
  }
  if(isset($role)){
    $bean = bean_block_view(strtolower($role).'-benefits');
    return theme('bean', $bean);
  }
}

function dfc_user_blocks_markup_wrapper($markup, $attributes = NULL, $tag = 'div') {
  if ( $tag == 'usermenu' ) {
    $output = '<span class="icon"></span><span class="title">'. $markup .'</span>';
    if (isset($attributes) && is_array($attributes)) {
      if ( isset( $attributes['count'] ) ) {
        $output .= '<span class="count">'. $attributes['count'] .'</span>';
      }
    }
  } else {
    $attrs = '';
    if (isset($attributes) && is_array($attributes)) {
      foreach($attributes as $k => $v) {
        $attrs .= " $k='$v'";
      }
    }
    $output = "<$tag$attrs>$markup</$tag>";
  }
  return $output;
}