<?php
/**
 * Implements hook_block_info().
 */
function dfc_user_blocks_block_info() {
  $blocks = array();
  $blocks['your_membership'] = array(
    'info' => t('Your Membership'),
  );
  $blocks['membership_benefits'] = array(
    'info' => t('Membership Benefits'),
  );
  $blocks['account_form'] = array(
    'info' => t('Account Form'),
  );
  return $blocks;
}

function dfc_user_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'your_membership':
      $block['content'] = array(
        '#markup' =>  dfc_user_blocks_your_membership_view()
      );
      break;
    case 'membership_benefits':
      $block['content'] = array(
        '#markup' =>  dfc_user_blocks_membership_benefits_view()
      );
      break;
    case 'account_form':
      $block['content'] = array(
        '#markup' =>  dfc_user_blocks_account_form_view()
      );
      break;
  }

  return $block;
}

function dfc_user_blocks_account_form_view(){
  global $user;
  $user=user_load($user->uid);
  module_load_include('inc', 'user', 'user.pages');
  $user_form = drupal_get_form('user_profile_form', $user);
  return drupal_render($user_form);
}

function dfc_user_blocks_your_membership_view(){
  global $user;
  $user = user_load($user->uid);
  foreach($user->roles as $role){
    if(in_array($role, array('Silver', 'Gold', 'Platinum', 'Diamond'))){
      break;
    }
  }
  // do we always show title?
  $markup = '<h3 class="membership-title">'. t('YOUR MEMBERSHIP') .'</h3>';
  // Current...  
  $current_markup = dfc_user_blocks_markup_wrapper( t('Current Membership Level:'), array('class' => 'current-membership-title'), 'h5' );
  $current_markup .= dfc_user_blocks_markup_wrapper($role, array('class' => 'current-role'), 'h2');
  //$current_markup .= dfc_user_blocks_markup_wrapper('Your annual membership is scheduled to auto-renew on ', array('class' => 'auto-renew'));
  $markup .= dfc_user_blocks_markup_wrapper($current_markup, array('class' => 'current-membership-wrapper'));
  // Upgrade...
  if($role <> 'Diamond'){
    $upgrade_markup = dfc_user_blocks_markup_wrapper( t('Want to upgrade?'), array('class' => 'upgrade-membership-title'), 'h5' );
    $upgrade_markup .= l(t('Membership Levels'), '/membership', array( 'attributes' => array( 'class' => array( 'button', 'button-small' ) ) ));
    $markup .= dfc_user_blocks_markup_wrapper($upgrade_markup, array('class' => 'upgrade-membership-wrapper'));
  }
  return $markup;
}

function dfc_user_blocks_membership_benefits_view(){
  global $user;
  $user = user_load($user->uid);
  foreach($user->roles as $role){
    if(in_array($role, array('Silver', 'Gold', 'Platinum', 'Diamond'))){
      break;
    }
  }
  if(isset($role)){
    $bean = bean_block_view(strtolower($role).'-benefits');
    return theme('bean', $bean);
  }
}

function dfc_user_blocks_markup_wrapper($markup, $attributes = NULL, $tag = 'div') {
  if ( $tag == 'usermenu' ) {
    $output = '<span class="icon"></span><span class="title">'. $markup .'</span>';
    if (isset($attributes) && is_array($attributes)) {
      if ( isset( $attributes['count'] ) ) {
        $output .= '<span class="count">'. $attributes['count'] .'</span>';
      }
    }
  } else {
    $attrs = '';
    if (isset($attributes) && is_array($attributes)) {
      foreach($attributes as $k => $v) {
        $attrs .= " $k='$v'";
      }
    }
    $output = "<$tag$attrs>$markup</$tag>";
  }
  return $output;
}

// hook_init per http://stackoverflow.com/a/32458844
function dfc_user_blocks_init() {
  /*
  if ( ( arg(0) == 'user' ) && ( arg(2) == 'edit' ) ) {
    drupal_goto('user/'. arg(1));
  }
  */
}
